providers/go/go.go, providers/npm/npm.go, providers/npmsearch/npmsearch.go, providers/youtube/youtube.go, s.go
Added npm, npmsearch, Go and YouTube search providers.
=> Add multiple providers

README.md
What is a name or username without a link?!
=> Added links to github profiles in the README

README.md, providers/quora/quora.go, s.go
[Quora](https://www.quora.com/about) is a fine Q&A website, I figured I could add a small contribution.
=> Add support to Quora

CONTRIBUTING.md
The `1.` is very personal but I do like to see that so we won't get a mess of commits for multiple providers.
=> Added some guidelines

providers/crunchyroll/crunchyroll.go, s.go
=> Add provider for searching anime on Crunchyroll

README.md, providers/nhaccuatui/nhaccuatui.go, s.go
=> Add nhaccuatui provider

README.md, providers/ietf/ietf.go, s.go
=> Add provider for searching IETF RFCs and Drafts

README.md, providers/atmospherejs/atmospherejs.go, s.go
Once again, sorry for messing up previous PRs a bit and thanks for a lesson in squashing commits :)
=> add atmospherejs provider

CONTRIBUTING.md
Maybe add to the README file to first read this.
=> Better explanation of contribution guidelines

README.md, providers/ifttt/ifttt.go, s.go
=> Add IFTTT provider

README.md, autocomplete/s-completion.bash
The provider list is rapidly increasing. So, thought of adding autocompletion to it. Let me know your view on this.
=> Support for provider autocompletion

README.md, providers/arxiv/arxiv.go, providers/arxiv/arxiv_test.go, s.go
Arxiv.org is a repo for e-prints, very useful for searching scientific papers.
=> Added provider arxiv.org

README.md, providers/linkedin/linkedin.go, s.go
Search provider on linkedin.com
=> Added provider Linkedin

.travis.yml
Run tests on go tip and all architectures.
=> Run tests on travis on linux, darwin and windows

providers/amazon/amazon.go, providers/providers.go
Added some hooks for people to get the users current region and language. Used them to add amazon.co.uk support.
=> Added hooks for devs to get region and language

README.md, providers/lmgtfy/lmgtfy.go, s.go
`s -p lmgtfy passive aggressive behavior`
=> Add provider for lmgtfy.com

README.md
I also wanted to add IE, but could not test it...
=> Add example on firefox incognito

README.md, providers/reddit/reddit.go, providers/reddit/reddit_test.go
Users should be able to search in subreddit with:
s -p reddit /r/cscareerquestions best startups.
=> Add support for search in subreddit

README.md, providers/inbox/inbox.go, s.go
The gmail provider doesn't work with Inbox.
=> Add Inbox By Gmail provider

README.md, providers/naver/naver.go, s.go
Added naver.com search engine for korean.
(Naver is the most famous search engine in Korea.)
=> Add naver.com as a provider

README.md, providers/instagram/instagram.go, s.go
Added instagram tag explore as a provider.
=> Add instagram.com tags explore as a provider

README.md, providers/torrentz/torrentz.go, s.go
Added Torrentz Provider with fixed with README.md conflict.
> Deleted old repository because of `single` commit.
=> Added Torrentz Provider

providers/amazon/amazon.go
- Australia
- Brazil
- Canada
- China
- France
- Germany
- India
- Italy
- Japan
- Mexico
- Netherlands
- Spain
=> Add Amazon for several countries

README.md, autocomplete/s-completion.bash, cmd/search.go, server/index.go, server/search.go, server/server.go, server/template.go
Added a simple web server to s. Features include:
* Loads all providers from s and allows quick searches in your browser.
* Smaller payload than any other search site.
* TLS support
* Gzip support
* Works identically on all modern desktop and mobile browsers.
* Added completion script options for cert and key.
=> Simple web server

README.md, cmd/config.go, cmd/search.go
Support for UCL based configuration file.
=> Added configuration file for s

README.md, autocomplete/s.fish
Adds support for provider completion for fish shell.
=> Fish completion

autocomplete/s.fish
fixes [issue](https://github.com/zquestz/s/pull/91#issuecomment-184981513) discussed in #91 . also, with this change, I was unable to reproduce [this issue](https://github.com/zquestz/s/pull/91#issuecomment-184981414)
=> fixes bug with call to "contains"

README.md
Get the Homebrew "bottle" if you don't want to explicitly use Go.
=> Instructions for Homebrew

autocomplete/s-completion.bash
_filedir (in newer bash completions) is a huge improvement
on compgen -f or compgen -G because it deals correctly with
spaces, ~ expansion, and .inputrc preferences. Falls back
on the existing glob if _filedir is unavailable.
`s <tab>` ought not to be completely silent.
=> Completion on empty invocation, and better path handling.

README.md, providers/shodan/shodan.go, s.go
Adds support for shodan.io.
https://github.com/zquestz/s/issues/111
=> Added shodan support

server/search.go
This just adds tag and provider expansion for the web front-end. Now we can do the following queries:
Search duckduckgo for "foo"
```
https://<domain>/search?q=foo&provider=duck
```
Search yahoo and the tag music for radiohead
```
https://<domain>/search?q=radiohead&provider=yah&tag=mu
```
@akb @tw4dl @mbhinder @lilirui @KeizerDev
=> Added tag and provider expansion for the web interface

.travis.yml
Updates .travis.yml to build binaries with 1.7.0.
@mbhinder @lilirui @variadico
=> Update builds to use 1.7.0

README.md, providers/cppreference/cppreference.go, s.go
Add the well-known cppreference as provider
=> Add cppreference as provider

README.md, allocine/allocine.go, providers/allocine/allocine.go, s.go
Added Allocine.fr provider (french movie website).
=> Add Allocine provider

README.md, providers/bigbasket/bigbasket.go, s.go
Adds provider for www.bigbasket.com
=> Adds Bigbasket provider

README.md, providers/magnetdl/magnetdl.go, s.go
searches magnet links via magnetdl.com
=> Add magnetdl.com provider

README.md, providers/pypi/pypi.go, s.go
Add [pypi.org](https://pypi.org) provider.
=> Add pypi provider

README.md, providers/pydoc/pydoc.go, s.go
=> Add pydoc provider

providers/perplexity/perplexity.go, s.go
Add provider for [perplexity](https://perplexity.ai).
=> Add provider for perplexity.ai

providers/phind/phind.go, s.go
Add provider for [phind](https://phind.com).
=> Add provider for phind.com

README.md, providers/flake8rules/flake8rules.go, s.go
Add provider for [flake8rules.com](https://flake8rules.com).
=> Add provider for flake8rules.com
